model:
  joint_ckpt: './logs_diffusion/training_2024_11_04__10_15_56/checkpoints/993000.pt'
  

sample:
  seed: 2025
  num_samples: 4
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior


